# Generated by Django 4.0.5 on 2022-06-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='prenume',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
