# Generated by Django 4.0.5 on 2022-06-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curs', '0002_student_prenume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=50)),
                ('an', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='an',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
