# Generated by Django 4.0.5 on 2022-06-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curs', '0005_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='an',
            field=models.IntegerField(default=1),
        ),
    ]
