# Generated by Django 4.0.5 on 2022-06-23 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curs', '0009_student_cursuri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cursuri',
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curs.curs')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curs.student')),
            ],
        ),
    ]
