# Generated by Django 4.0.5 on 2022-06-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curs', '0010_remove_student_cursuri_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cursuri',
            field=models.ManyToManyField(through='curs.Membership', to='curs.curs'),
        ),
    ]
